spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.8.88:3306/management_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: Js@20201111

logging:
  config: classpath:logging.xml
log:
  name: management_platform
  path: /js/logs/
  level: info

minio:
  bucketName: test
  endpoint: http://192.168.8.88:9000
  accessKey: jsAdmin
  secretKey: Js@20201111
